version: '3'
services:
  ipfs:
    # docker run -d --name ipfs_host -v $ipfs_staging:/export -v $ipfs_data:/data/ipfs -p 4001:4001 -p 127.0.0.1:8080:8080 -p 127.0.0.1:5001:5001 ipfs/go-ipfs:latest
    image: ipfs/kubo:latest
    restart: unless-stopped
    ports:
      - 4001:4001
      - 8080:8080
      - 5001:5001
    volumes:
      # - type: bind
      #   source: ./staging_dir
      #   target: /export
      # - type: bind
      #   source: ./data_dir
      #   target: /data/ipfs
      - ./staging_dir:/export
      # - ./data_dir:/data/ipfs
      - ipfs:/data/ipfs
    networks:
      - honeycomb
  honeycomb:
    # depends_on:
    #   - ipfs
    build: .
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - ipfshost=ipfs
      - ipfsprotocol=http
      - ipfsport=5001
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    # stdin_open: true
    # tty: true
    stdin_open: true
    tty: true
    networks:
      - honeycomb
  # node-2:
  #   image: ipfs/go-ipfs:latest
  #   build:
  #     context: private-network
  #   environment:
  #     LIBP2P_FORCE_PNET: '1'
  #     # SWARM_KEY: "/key/swarm/psk/1.0.0/\n/base16/\ne0e7b1394fb6e928eecf2f8db77eaa99d3657684dc939519f285cb902bd93e22"
  #   volumes:
  #     - node-2:/data/ipfs
  #     - ./private-network/.ipfs/swarm.key:/data/ipfs/swarm.key
  #     - ./private-network/init.sh:/usr/local/bin/start_ipfs
  #   ports:
  #     - 8080
  # node-3:
  #   build:
  #     context: private-network
  #   environment:
  #     LIBP2P_FORCE_PNET: '1'
  #     # SWARM_KEY: "/key/swarm/psk/1.0.0/\n/base16/\ne0e7b1394fb6e928eecf2f8db77eaa99d3657684dc939519f285cb902bd93e22"
  #     SWARM_PEER: /ip4/172.18.0.2/tcp/4001/ipfs/QmUrp1E4ArW1ZDdFHnQrKfdH8tgGxM38hmPyjXEEoTmfto
  #   volumes:
  #     - node-3:/data/ipfs
  #     - ./private-network/.ipfs/swarm.key:/data/ipfs/swarm.key
  #     - ./private-network/init.sh:/usr/local/bin/start_ipfs
  #   ports:
  #     - 8080
volumes:
  ipfs:
  # node-2:
  # node-3:

networks:
  honeycomb:
